name: Deploy to surge

on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    name: "Deploy Branch to Surge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # Install dependencies
      - name: Install dependencies
        run: yarn
      # Build the project
      - name: Build
        run: yarn build

      # Deploy to surge
      - name: Install Surge Globally      
        run: npm install --global surge
      - name: Deploy to Surge
        run: surge  ./dist fair-protocol-${{ github.ref_name }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}